version: '3.4'
services:
  grpc-server:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: server
    command: ["pipenv", "run", "start"]
    ports:
      - "5000:5000"
    environment:
      - "GRPC_PORT=5000"
  envoy:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: envoy
    command: ["envoy", "-c", "/config/config.yaml"]
    ports:
      - "50051:50051"
